"""normalize bank remittance journal tables

Revision ID: 8783837c2904
Revises: a21dc801bd42
Create Date: 2026-03-19 13:27:05.797997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8783837c2904'
down_revision: Union[str, Sequence[str], None] = 'a21dc801bd42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_statement_headers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blob_object_id', sa.UUID(), nullable=False),
    sa.Column('sheet_name', sa.String(length=120), nullable=False),
    sa.Column('source_file_name', sa.String(length=255), nullable=True),
    sa.Column('statement_currency', sa.String(length=3), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('total_credit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_debit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blob_object_id'], ['blob_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blob_object_id')
    )
    op.create_table('remittance_advice_headers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blob_object_id', sa.UUID(), nullable=False),
    sa.Column('advice_number', sa.String(length=80), nullable=True),
    sa.Column('advice_date', sa.Date(), nullable=True),
    sa.Column('payer_name', sa.String(length=255), nullable=True),
    sa.Column('payer_iban', sa.String(length=64), nullable=True),
    sa.Column('payer_bic', sa.String(length=20), nullable=True),
    sa.Column('document_currency', sa.String(length=3), nullable=True),
    sa.Column('total_paid_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('document_language', sa.String(length=10), nullable=False),
    sa.Column('remittance_subject', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_engine', sa.String(length=40), nullable=True),
    sa.Column('parsing_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blob_object_id'], ['blob_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blob_object_id')
    )
    op.create_table('bank_statement_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statement_header_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('payment_purpose', sa.Text(), nullable=True),
    sa.Column('counterparty_account', sa.String(length=64), nullable=True),
    sa.Column('bic', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_code', sa.String(length=20), nullable=True),
    sa.Column('booking_text', sa.String(length=120), nullable=True),
    sa.Column('bank_reference', sa.String(length=120), nullable=True),
    sa.Column('iban', sa.String(length=64), nullable=True),
    sa.Column('account_label', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=40), nullable=True),
    sa.Column('customer_reference', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['statement_header_id'], ['bank_statement_headers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('statement_header_id', 'line_number', name='uq_bank_line_number')
    )
    op.create_table('journal_entry_headers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('company_code', sa.String(length=20), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('document_type', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_file_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remittance_advice_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('advice_header_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=80), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('deduction_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('customer_reference', sa.String(length=120), nullable=True),
    sa.Column('assignment_text', sa.Text(), nullable=True),
    sa.Column('raw_line_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['advice_header_id'], ['remittance_advice_headers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advice_header_id', 'line_number', name='uq_remittance_line_number')
    )
    op.create_table('reconciliation_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('bank_statement_line_id', sa.UUID(), nullable=False),
    sa.Column('remittance_advice_line_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('AUTO_MATCHED', 'PARTIAL_MATCH', 'UNMATCHED', 'MANUAL_REVIEW', name='matchstatus'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('match_rule', sa.String(length=80), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('variance_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_statement_line_id'], ['bank_statement_lines.id'], ),
    sa.ForeignKeyConstraint(['remittance_advice_line_id'], ['remittance_advice_lines.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entry_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_header_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('gl_account', sa.String(length=20), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('item_text', sa.String(length=255), nullable=True),
    sa.Column('reconciliation_match_id', sa.UUID(), nullable=True),
    sa.Column('bank_statement_line_id', sa.UUID(), nullable=True),
    sa.Column('remittance_advice_line_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bank_statement_line_id'], ['bank_statement_lines.id'], ),
    sa.ForeignKeyConstraint(['journal_header_id'], ['journal_entry_headers.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_match_id'], ['reconciliation_matches.id'], ),
    sa.ForeignKeyConstraint(['remittance_advice_line_id'], ['remittance_advice_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_header_id', 'line_number', name='uq_journal_line_number')
    )
    op.drop_table('journal_entries')
    op.drop_table('match_results')
    op.drop_table('remittance_lines')
    op.drop_table('bank_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remittance_lines',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('blob_object_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('paid_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('customer_reference', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blob_object_id'], ['blob_objects.id'], name=op.f('remittance_lines_blob_object_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('remittance_lines_pkey'))
    )
    op.create_table('match_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bank_transaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('remittance_line_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('match_rule', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], name=op.f('match_results_bank_transaction_id_fkey')),
    sa.ForeignKeyConstraint(['remittance_line_id'], ['remittance_lines.id'], name=op.f('match_results_remittance_line_id_fkey')),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], name=op.f('match_results_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('match_results_pkey'))
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_match_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('entry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('gl_account_debit', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('gl_account_credit', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], name=op.f('journal_entries_run_id_fkey')),
    sa.ForeignKeyConstraint(['source_match_id'], ['match_results.id'], name=op.f('journal_entries_source_match_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_entries_pkey'))
    )
    op.create_table('bank_transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('blob_object_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('booking_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('value_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('bank_reference', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('payer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blob_object_id'], ['blob_objects.id'], name=op.f('bank_transactions_blob_object_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bank_transactions_pkey'))
    )
    op.drop_table('journal_entry_lines')
    op.drop_table('reconciliation_matches')
    op.drop_table('remittance_advice_lines')
    op.drop_table('journal_entry_headers')
    op.drop_table('bank_statement_lines')
    op.drop_table('remittance_advice_headers')
    op.drop_table('bank_statement_headers')
    # ### end Alembic commands ###
