"""create metadata tables

Revision ID: a21dc801bd42
Revises: 
Create Date: 2026-03-19 13:12:53.485223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a21dc801bd42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('blob_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('BANK_STATEMENT', 'REMITTANCE', name='sourcetype'), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('container_name', sa.String(length=120), nullable=False),
    sa.Column('blob_path', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_type', 'business_date', 'content_hash', name='uq_blob_dedup')
    )
    op.create_table('bank_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blob_object_id', sa.UUID(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('bank_reference', sa.String(length=120), nullable=True),
    sa.Column('payer_name', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['blob_object_id'], ['blob_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PARSED', 'MATCHED', 'POSTED', 'FAILED', name='runstatus'), nullable=False),
    sa.Column('bank_blob_id', sa.UUID(), nullable=True),
    sa.Column('remittance_blob_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bank_blob_id'], ['blob_objects.id'], ),
    sa.ForeignKeyConstraint(['remittance_blob_id'], ['blob_objects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remittance_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blob_object_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=120), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('customer_reference', sa.String(length=120), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['blob_object_id'], ['blob_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('bank_transaction_id', sa.UUID(), nullable=False),
    sa.Column('remittance_line_id', sa.UUID(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('match_rule', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ),
    sa.ForeignKeyConstraint(['remittance_line_id'], ['remittance_lines.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source_match_id', sa.UUID(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('gl_account_debit', sa.String(length=20), nullable=False),
    sa.Column('gl_account_credit', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['source_match_id'], ['match_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_entries')
    op.drop_table('match_results')
    op.drop_table('remittance_lines')
    op.drop_table('ingestion_runs')
    op.drop_table('bank_transactions')
    op.drop_table('blob_objects')
    op.drop_table('tenants')
    # ### end Alembic commands ###
