"""add run statuses provenance and audit

Revision ID: ce9049704dc3
Revises: 8783837c2904
Create Date: 2026-03-19 13:51:40.998679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce9049704dc3'
down_revision: Union[str, Sequence[str], None] = '8783837c2904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enum value expansion for existing Postgres enum types.
    op.execute("ALTER TYPE runstatus ADD VALUE IF NOT EXISTS 'REVIEW_REQUIRED'")
    op.execute("ALTER TYPE runstatus ADD VALUE IF NOT EXISTS 'READY_TO_POST'")
    op.execute("ALTER TYPE matchstatus ADD VALUE IF NOT EXISTS 'APPROVED'")
    op.execute("ALTER TYPE matchstatus ADD VALUE IF NOT EXISTS 'REJECTED'")
    op.execute("ALTER TYPE matchstatus ADD VALUE IF NOT EXISTS 'CLOSED'")

    op.create_table('match_action_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.String(length=120), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['reconciliation_matches.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ingestion_runs', sa.Column('review_reason_code', sa.String(length=64), nullable=True))
    op.add_column(
        'ingestion_runs',
        sa.Column('parsed_line_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'ingestion_runs',
        sa.Column('matched_line_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'ingestion_runs',
        sa.Column('review_required_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'reconciliation_matches',
        sa.Column('source', sa.String(length=32), nullable=False, server_default='RULE'),
    )
    op.add_column('reconciliation_matches', sa.Column('reviewed_by', sa.String(length=120), nullable=True))
    op.add_column('reconciliation_matches', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reconciliation_matches', sa.Column('review_comment', sa.Text(), nullable=True))
    op.add_column(
        'reconciliation_matches',
        sa.Column('is_selected', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    )
    op.add_column('remittance_advice_headers', sa.Column('extraction_method', sa.String(length=32), nullable=True))
    op.add_column('remittance_advice_headers', sa.Column('llm_model', sa.String(length=120), nullable=True))
    op.add_column('remittance_advice_headers', sa.Column('llm_prompt_version', sa.String(length=40), nullable=True))
    op.add_column('remittance_advice_headers', sa.Column('raw_llm_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('remittance_advice_headers', sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('remittance_advice_headers', sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('ingestion_runs', 'parsed_line_count', server_default=None)
    op.alter_column('ingestion_runs', 'matched_line_count', server_default=None)
    op.alter_column('ingestion_runs', 'review_required_count', server_default=None)
    op.alter_column('reconciliation_matches', 'source', server_default=None)
    op.alter_column('reconciliation_matches', 'is_selected', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remittance_advice_headers', 'validation_errors')
    op.drop_column('remittance_advice_headers', 'normalized_payload')
    op.drop_column('remittance_advice_headers', 'raw_llm_output')
    op.drop_column('remittance_advice_headers', 'llm_prompt_version')
    op.drop_column('remittance_advice_headers', 'llm_model')
    op.drop_column('remittance_advice_headers', 'extraction_method')
    op.drop_column('reconciliation_matches', 'is_selected')
    op.drop_column('reconciliation_matches', 'review_comment')
    op.drop_column('reconciliation_matches', 'reviewed_at')
    op.drop_column('reconciliation_matches', 'reviewed_by')
    op.drop_column('reconciliation_matches', 'source')
    op.drop_column('ingestion_runs', 'review_required_count')
    op.drop_column('ingestion_runs', 'matched_line_count')
    op.drop_column('ingestion_runs', 'parsed_line_count')
    op.drop_column('ingestion_runs', 'review_reason_code')
    op.drop_table('match_action_audit')
    # ### end Alembic commands ###
